name: MyPanel
version: 1.0
main: top.allenme.mypanel.MyPanel
api-version: 1.13
commands:
  server:
    description: View server status page
    usage: /<command>
  player:
    description: View your player status page
    usage: /<command>